### PR TITLE
Use ReverseWordMap to make O(1) lookups for IsMnemonicValid

### PR DESCRIPTION
**Pull request by odeke-em**
Noticed while auditing a dependency of Cosmos-sdk code from
PR https://github.com/cosmos/cosmos-sdk/pull/8099, WordList
is loaded at init time, and so is ReverseWordMap.
Usually a slice is sufficient for doing linear lookups for
the existence of a string. However, given that IsMnemonicValid
requires word segements with 12 to 24 lengths, this means that
2048 * ~12 lookups in the worst case, and given that we already
at init time load up ReverseWordMap, it is important for us
perform a constant time lookup. The data also backs up the speed up
with the benchmark results below:

```shell
name               old time/op    new time/op    delta
IsMnemonicValid-8    24.3µs ± 1%     1.3µs ± 1%  -94.64%  (p=0.000 n=9+10)

name               old alloc/op   new alloc/op   delta
IsMnemonicValid-8      576B ± 0%      576B ± 0%     ~     (all equal)

name               old allocs/op  new allocs/op  delta
IsMnemonicValid-8      3.00 ± 0%      3.00 ± 0%     ~     (all equal)
```

### CODE REVIEW

**Comment by odeke-em** [comment]
Kindly cc-ing prior code authors/contributors @okwme @alessio @alexanderbez.

**Comment by alessio** [comment]
I've run the tests and got a failure (they run fine in `master`):

```
alessio@phoenix:~/work/go-bip39$ go test ./...
--- FAIL: TestBip39 (0.00s)
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 19 [running]:
testing.tRunner.func1.1(0x603540, 0xc00014c480)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000102900)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x603540, 0xc00014c480)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
encoding/binary.bigEndian.Uint16(...)
	/usr/local/go/src/encoding/binary/binary.go:101
github.com/cosmos/go-bip39.NewMnemonic(0xc00014c440, 0x10, 0x20, 0x0, 0x0, 0x0, 0x0)
	/home/alessio/work/go-bip39/bip39.go:80 +0x477
github.com/cosmos/go-bip39.TestBip39(0xc000102900)
	/home/alessio/work/go-bip39/bip39_test.go:21 +0x1b4
testing.tRunner(0xc000102900, 0x630f18)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
FAIL	github.com/cosmos/go-bip39	0.004s
FAIL
```

_(It's unfortunate that don't have CI here)_

**Comment by odeke-em** [comment]
Thank you @alessio for running it, I've reverted the padByteSlice change and now all gucci, please take another look.

**Comment by alessio** [comment]
It works like a charm. Good to go!

**Comment by odeke-em** [comment]
Thank you for the review @alessio! Please help me cut a new release aka tag, and then that can be included in cosmos-sdk as a speedier dependency.

**Comment by alessio** [comment]
@odeke-em I could simply tag a `v1.0.0` right away on `master`. Would that work for you?

**Comment by odeke-em** [comment]
Yes please, that would work, thank you!

**Comment by alessio** [comment]
Done https://github.com/cosmos/go-bip39/releases/tag/v1.0.0

**Pull request merged**
